### PR TITLE
e2e: fixes TimeRange set function

### LINKED ISSUE #1716: Bug: TimeRange zone selection issue
### Which package(s) does this bug affect?

- [ ] Create Plugin
- [ ] Sign Plugin
- [x] Plugin E2E
- [ ] Plugin Meta Extractor
- [ ] Plugin ESLint Rules

### Package versions

```shell
1.17.1
```

### What happened?

In playwright test when editPanelPage.timeRange.set function is invoked 
component 'packages/plugin-e2e/src/models/components/TimeRange.ts' at line 28 'fill...' times out 

`await this.getByGrafanaSelector(TimeZonePicker.containerV2).fill(zone);`

with next error:

`Error: locator.fill: Error: Element is not an <input>, <textarea>, <select> or [contenteditable] and does not have a role allowing [aria-readonly]`

### What you expected to happen

From, To, Zone information should be properly set into Grafana's Time Range.

### How to reproduce it (as minimally and precisely as possible)

1. any environment
2. any config
3. any  grafana e2e test with injected `panelEditPage` run `panelEditPage.timeRange.set({zone: "Coordinated Universal Time"})`
4. the function fails

### Environment

```shell
System:
    OS: macOS 15.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 342.48 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.13.1 - /opt/homebrew/bin/node
    npm: 10.9.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 135.0.7049.43
    Safari: 18.4
  npmPackages:
    @grafana/data: ^10.4.0 => 10.4.17 
    @grafana/eslint-config: ^8.0.0 => 8.0.0 
    @grafana/plugin-e2e: ^1.17.1 => 1.19.3 
    @grafana/plugin-ui: ^0.9.6 => 0.9.6 
    @grafana/runtime: ^10.4.0 => 10.4.17 
    @grafana/schema: ^10.4.0 => 10.4.17 
    @grafana/tsconfig: ^2.0.0 => 2.0.0 
    @grafana/ui: ^10.4.0 => 10.4.17
```

### Additional context

In order to fix it 'packages/plugin-e2e/src/models/components/TimeRange.ts' at line 28 should be replaced with next code

```
        await this.getByGrafanaSelector(TimeZonePicker.containerV2).click();
        await this.getByGrafanaSelector(selectors.components.Select.option).filter({hasText: zone}).click()
```

### PR DESCRIPTION
**Pull request by hugohaggmark**
**What this PR does / why we need it**:
This PR fixes the `TimeRange.set` function so it works when a test uses the `zone` argument.

**Which issue(s) this PR fixes**:

Fixes #1716

**Special notes for your reviewer**:
1. Scaffold a new panel plugin
2. Follow the instructions, `npm install` ...etc
3. In the `panel.spec.ts` file add the following test
```ts
test('should set correct time range', async ({ gotoPanelEditPage, readProvisionedDashboard, page }) => {
  const dashboard = await readProvisionedDashboard({ fileName: 'dashboard.json' });
  const panelEditPage = await gotoPanelEditPage({ dashboard, id: '1' });
  await panelEditPage.timeRange.set({ zone: 'Coordinated Universal Time', from: 'now-1h', to: 'now' });
});
```
4. In a terminal run `npm run server` wait for Grafana image to start
5. In an other terminal run `npm run e2e`
6. The new test should fail [NOT OK] 🛑 
7. Install the canary version of plugin-e2e from this PR 
8. In the same terminal run `npm run e2e` 
9. The new test should now pass [OK] ✅  

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @grafana/plugin-e2e@1.19.7-canary.1735.14492280495.0
  # or 
  yarn add @grafana/plugin-e2e@1.19.7-canary.1735.14492280495.0
  ```
</details>

### CODE REVIEW

File: packages/plugin-e2e/src/models/components/TimeRange.ts [hunk 1]
```diff
@@ -25,7 +25,8 @@ export class TimeRange extends GrafanaPage {
         : this.ctx.page.getByRole('button', { name: 'Change time settings' });
 
       await changeTimeSettingsButton.click();
-      await this.getByGrafanaSelector(TimeZonePicker.containerV2).fill(zone);
+      await this.getByGrafanaSelector(TimeZonePicker.containerV2).click();
```
Comment (jackw) [inline packages/plugin-e2e/src/models/components/TimeRange.ts:28]: Is this a bug related to plugin-e2e or has something changed in Grafana which means we need to apply a change here? Asking in case we need to guard against different versions of Grafana.

Comment (hugohaggmark) [reply packages/plugin-e2e/src/models/components/TimeRange.ts:28]: I've tried this in Grafana 9.0 and 10.2 and the `zone` code doesn't seem to have ever worked. When I use this fix in Grafana 9 or 10.2 it works as expected. So this is a bug in plugin-e2e IMHO 👍

**Review by jackw — APPROVED** [review]
LGTM! 🚀
