### PR TITLE
Fix: Making plugin id schema compliant

### LINKED ISSUE #92: Generated plugin.json does not contain `keywords` field
`keywords` is a required field based on our plugin.json schema.

### PR DESCRIPTION
**Pull request by tolzhabayev**
Fixing plugin id's to make them schema compliant

### CODE REVIEW

**Comment by tolzhabayev** [comment]
duplicate of https://github.com/grafana/plugin-tools/pull/93

**Review by academo — APPROVED** [review]

File: packages/create-plugin/scripts/generate-panel.js [hunk 1]
```diff
@@ -11,8 +11,8 @@ async function generatePanel() {
   const plop = await nodePlop(plopFile);
   const generator = plop.getGenerator('create-plugin');
   await generator.runActions({
-    pluginName: 'my-plugin',
-    orgName: 'my-org',
+    pluginName: 'myplugin',
```
Comment (jackw) [inline packages/create-plugin/scripts/generate-panel.js:14]: Rather than change these shouldn't we do something with `normalize_id` so whatever the input is the output is schema compliant?

Comment (tolzhabayev) [reply packages/create-plugin/scripts/generate-panel.js:14]: good idea, will update my PR

Comment (academo) [reply packages/create-plugin/scripts/generate-panel.js:14]: These inputs are equivalent to user input.

File: packages/create-plugin/src/utils/utils.handlebars.ts [hunk 2]
```diff
@@ -12,8 +12,12 @@ export const ifEq = (a: any, b: any, options: HelperOptions) => {
 
 export const normalizeId = (pluginName: string, orgName: string, type: PLUGIN_TYPES) => {
   const re = new RegExp(`-?${type}$`, 'i');
-  const newPluginName = pluginName.replace(re, '');
-  return changeCase.paramCase(orgName) + '-' + changeCase.paramCase(newPluginName) + `-${type}`;
+  const pluginNameRegex = new RegExp('[^0-9a-z]', 'g');
```
Comment (academo) [inline packages/create-plugin/src/utils/utils.handlebars.ts:15]: These two regex are the same you can reuse one. what about `nameRegex``

Comment (tolzhabayev) [reply packages/create-plugin/src/utils/utils.handlebars.ts]: Right, https://github.com/grafana/plugin-tools/pull/95/commits/8cb1fc172605d6dedc615a4c0dfc9a22c5899cb8
