### PR TITLE
PluginE2E: Move away from networkIdle

### LINKED ISSUE #1734: Plugin E2E: Move away from waitUntil: 'networkidle'
With newer releases of playwright we have a need to remove the usage of `waitUntil: 'networkidle'` when navigating pages. This is due to the playwright team enabling the [PlzDedicatedWorker feature in chromium](https://github.com/microsoft/playwright/pull/34400) which causes e2e test failures that look something like this:

`navigating to "http://localhost:3000/XYZ", waiting until "networkidle"`

`networkidle` is the default used by plugin-e2e in the GrafanaPage [here](https://github.com/grafana/plugin-tools/blob/main/packages/plugin-e2e/src/models/pages/GrafanaPage.ts#L22) model when going to a page. However the docs related to [page.goto()](https://playwright.dev/docs/api/class-page#page-goto) discourage it's usage:

>DISCOURAGED consider operation to be finished when there are no network connections for at least 500 ms. Don't use this method for testing, rely on web assertions to assess readiness instead.

See https://github.com/grafana/plugin-tools/pull/1728

### LINKED ISSUE #1745: e2e: waiting until "networkidle" error
### Which package(s) does this bug affect?

- [ ] Create Plugin
- [ ] Sign Plugin
- [x] Plugin E2E
- [ ] Plugin Meta Extractor
- [ ] Plugin ESLint Rules

### Package versions

```shell
"@grafana/plugin-e2e": "1.19.8"
"@playwright/test": "1.52.0"
```

### What happened?

Can be similar with #1734 
Refer to [pull/1741](https://github.com/grafana/plugin-tools/pull/1741#issuecomment-2821247066)

We are still experiencing the timeout issue with the latest versions of the e2e and @playwright/test packages. It occurs for all versions above 11.5.1.

Here is PR with issue: https://github.com/VolkovLabs/business-table/pull/308
and run: https://github.com/VolkovLabs/business-table/actions/runs/14615895268/job/41003960560?pr=308

All tests are encountering the same error:
```js
 Error: page.goto: Test timeout of 30000ms exceeded.
test-1  |     Call log:
test-1  |       - navigating to "http://127.0.0.1:3000/d/ee576vdnqy7eoc", waiting until "networkidle"
```

Image

Here is the package configuration: 
```json
 "dependencies": {
    "@emotion/css": "^11.13.5",
    "@floating-ui/react": "^0.27.8",
    "@grafana/data": "^11.6.0",
    "@grafana/runtime": "^11.6.0",
    "@grafana/scenes": "^6.9.1",
    "@grafana/ui": "^11.6.0",
    "@hello-pangea/dnd": "^18.0.1",
    "@react-aria/focus": "^3.20.2",
    "@tanstack/react-table": "^8.21.3",
    "@tanstack/react-virtual": "^3.13.6",
    "@volkovlabs/components": "^4.4.0",
    "file-saver": "^2.0.5",
    "js-base64": "^3.7.7",
    "markdown-it": "^14.1.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "semver": "^7.7.1",
    "tslib": "^2.8.0",
    "uuid": "^11.1.0",
    "xlsx": "^0.18.5"
  },
  "description": "Simplify data visualization in table format",
  "devDependencies": {
    "@grafana/eslint-config": "^8.0.0",
    "@grafana/plugin-e2e": "1.19.8",
    "@grafana/tsconfig": "^2.0.0",
    "@playwright/test": "1.52.0",
    "@stylistic/eslint-plugin-ts": "^2.13.0",
    "@swc/core": "^1.11.21",
    "@swc/helpers": "^0.5.17",
    "@swc/jest": "^0.2.37",
    "@testing-library/jest-dom": "^6.6.3",
    "@testing-library/react": "^16.3.0",
    "@types/file-saver": "^2.0.7",
    "@types/jest": "^29.5.14",
    "@types/lodash": "^4.17.16",
    "@types/markdown-it": "^14.1.2",
    "@types/node": "^22.14.1",
    "@types/uuid": "^10.0.0",
    "@volkovlabs/eslint-config": "^1.3.0",
    "@volkovlabs/jest-selectors": "^1.5.0",
    "copy-webpack-plugin": "^12.0.2",
    "css-loader": "^7.1.2",
    "eslint": "^8.57.1",
    "eslint-plugin-deprecation": "^3.0.0",
    "eslint-webpack-plugin": "^4.2.0",
    "fork-ts-checker-webpack-plugin": "^9.1.0",
    "glob": "^11.0.1",
    "identity-obj-proxy": "3.0.0",
    "jest": "^29.7.0",
    "jest-environment-jsdom": "^29.7.0",
    "prettier": "^3.5.3",
    "replace-in-file-webpack-plugin": "^1.0.6",
    "sass": "^1.87.0",
    "sass-loader": "^16.0.5",
    "style-loader": "^4.0.0",
    "swc-loader": "^0.2.6",
    "ts-node": "^10.9.2",
    "tsconfig-paths": "^4.2.0",
    "tsconfig-paths-webpack-plugin": "^4.2.0",
    "typescript": "^5.8.3",
    "webpack": "^5.99.6",
    "webpack-cli": "^6.0.1",
    "webpack-livereload-plugin": "^3.0.2"
  }
```

If we revert to the previous versions, the tests pass

```json
"@grafana/plugin-e2e": "1.17.1",
"@playwright/test": "1.50.1",
```

As you may notice, we are running tests for three different versions:

dep: 10.3 - tests work as expected.

main: 12.0.0 - 'waiting until networkidle' error.

dev: 11.5.1 - 'waiting until networkidle' error.

For example, the createDataSourceConfigPage methods are not working either.

### What you expected to happen

The error related to 'waiting until networkidle'  should not occur.

### How to reproduce it (as minimally and precisely as possible)

See the problem description

### Environment

```shell
System:
    OS: Linux 6.8 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-12650H
    Memory: 4.01 GB / 15.35 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
  Browsers:
    Chrome: 135.0.7049.84
  npmPackages:
    @grafana/data: ^11.6.0 => 11.6.0 
    @grafana/eslint-config: ^8.0.0 => 8.0.0 
    @grafana/plugin-e2e: 1.19.8 => 1.19.8 
    @grafana/runtime: ^11.6.0 => 11.6.0 
    @grafana/scenes: ^6.9.1 => 6.9.1 
    @grafana/tsconfig: ^2.0.0 => 2.0.0 
    @grafana/ui: ^11.6.0 => 11.6.0
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jackw**
**What this PR does / why we need it**:

The last 2 minor releases of playwright have caused multiple issues (#1606 , #1728 , #1740 , #1741) with plugin-e2e due to changes with using chromiums headless browser and workers picking up events in different ways. This is mainly surfaced with timeouts due to `networkIdle` being used across all the plugin-e2e page models to wait for a page to load when navigating.

This PR switches `networkIdle` out for `load` (which is the default), fixes up any of the issues we can easily identify from the tests in this repo, and continues to allow developers to set the `waitUntil` property as they see fit.

Once we're confident these tests are not flakey we'll move on to testing a canary build of plugin-e2e in Grafana before merging.

**Which issue(s) this PR fixes**:

Fixes #1734
Fixes #1745

**Special notes for your reviewer**:

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @grafana/plugin-e2e@2.0.0-canary.1746.14835096080.0
  # or 
  yarn add @grafana/plugin-e2e@2.0.0-canary.1746.14835096080.0
  ```
</details>

### CODE REVIEW

File: packages/plugin-e2e/src/models/pages/AlertRuleEditPage.ts [hunk 1]
```diff
@@ -41,10 +42,18 @@ export class AlertRuleEditPage extends GrafanaPage {
...
+      'alertingQueryAndExpressionsStepMode'
+    );
+
+    if (alertingQueryAndExpressionsStepMode) {
+      await expect(this.advancedModeSwitch).toBeVisible();
+    } else {
+      await expect(this.advancedModeSwitch).not.toBeVisible();
+    }
+
+    const count = await this.advancedModeSwitch.count();
```
Comment (andresmgot) [inline packages/plugin-e2e/src/models/pages/AlertRuleEditPage.ts:56]: maybe I am reading this wrong but shouldn't this `.count` be made only if `alertingQueryAndExpressionsStepMode`? or maybe if it's not visible this will still return a count >0

File: packages/plugin-e2e/tests/as-admin-user/datasource/query-editor/queryEditor.integration.spec.ts [hunk 2]
```diff
@@ -33,3 +33,5 @@ test('should be possible to load and execute an existing valid query', async ({
   await expect(panelEditPage.refreshPanel()).toBeOK();
   await expect(panelEditPage.panel.getErrorIcon()).not.toBeVisible();
 });
+
+// DEBUG=pw:browser
```
Comment (andresmgot) [inline packages/plugin-e2e/tests/as-admin-user/datasource/query-editor/queryEditor.integration.spec.ts:37]: is this annotation needed?

**Review by andresmgot — APPROVED** [review]
LGTM, a couple of nits

File: packages/plugin-e2e/tests/as-admin-user/datasource/query-editor/queryEditor.integration.spec.ts (hunk 2 above)
Comment (jackw) [reply packages/plugin-e2e/tests/as-admin-user/datasource/query-editor/queryEditor.integration.spec.ts]: Nope, not needed. Thanks for spotting this.

File: packages/plugin-e2e/src/models/pages/AlertRuleEditPage.ts (hunk 1 above)
Comment (hugohaggmark) [reply packages/plugin-e2e/src/models/pages/AlertRuleEditPage.ts]: Great find, changed it now 👍
