### PR TITLE
Fix eslint not generating in plugin migrations

### LINKED ISSUE #606: bug: eslintrc file is missing when running migrate command
When migrating a project from toolkit I ran `yarn create @grafana/plugin migrate` and answered yes to everything.

It successfully added https://github.com/grafana/plugin-tools/blob/main/packages/create-plugin/templates/common/.config/_eslintrc

But failed to add https://github.com/grafana/plugin-tools/blob/main/packages/create-plugin/templates/common/_eslintrc

This causes the plugin to fail to build with a warning about no eslint config found in src. 

To reproduce, this was the repository prior to any changes https://github.com/raulsperoni/magnesium-wordcloud-panel/releases/tag/v1.2.4

### PR DESCRIPTION
**Pull request by academo**
**What this PR does / why we need it**:

Fixes an issue where the eslintrc file was not generated when migrating a plugin using the migrate command.

This now correctly generates the eslintrc file in both migrate and update

**Which issue(s) this PR fixes**:

fixes https://github.com/grafana/plugin-tools/issues/606

**Special notes for your reviewer**:

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @grafana/create-plugin@2.12.0-canary.624.65b1c50.0
  npm install @grafana/plugin-e2e@0.9.0-canary.624.65b1c50.0
  # or 
  yarn add @grafana/create-plugin@2.12.0-canary.624.65b1c50.0
  yarn add @grafana/plugin-e2e@0.9.0-canary.624.65b1c50.0
  ```
</details>

### CODE REVIEW

File: packages/create-plugin/src/utils/utils.templates.ts [hunk 1]
```diff
@@ -23,9 +23,13 @@ export function getTemplateFiles(pluginType: string, filter?: string | string[])
...
     return templateFiles.filter((file) => {
-      const projectRelativePath = getProjectRelativeTemplatePath(file, pluginType);
+      const fileProjectRelativePath = getProjectRelativeTemplatePath(file, pluginType);
+      const exportedName = path.join(path.dirname(fileProjectRelativePath), getExportFileName(fileProjectRelativePath));
 
-      return isFileStartingWith(projectRelativePath, filter);
+      // note: some files to filter might use their exported name instead of
+      // their template version e.g. _eslint instead of .eslint.
+      // We need to check the filter with both of them to prevent skipping them in an update or migration
+      return isFileStartingWith(fileProjectRelativePath, filter) || isFileStartingWith(exportedName, filter);
```
Comment (academo) [inline packages/create-plugin/src/utils/utils.templates.ts:32]: @jackw my alternative fix to have a double check here is to have an inverse function to `getExportFileName` such as `getTemplateFileName` which would transform the list of files to migrate to their "template" version and then the rest of the code handles it correctly.

**Review by jackw — APPROVED** [review]
LGTM! 🚀
